spring:
  application:
    name: talis-web-management
  datasource:
    url: jdbc:mysql://localhost:3306/talis
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 8773
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    map-underscore-to-camel-case: true
    #配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    bucketName: java-czx1
    region: cn-beijing